password = "password"

open_ai_api_key = "sk-...."
open_ai_api_model = "gpt-3.5-turbo" # optional, should be set for openai api

# open_ai_api_type = "openai" # or azure # optional, should be set for azure api
# open_ai_api_base = "https://api.openai.com/v1" # optional, should be set for azure api
# open_ai_api_version = "" # optional, should be set for azure api
# open_ai_engine = "gpt-3.5-turbo" # optional, should be set for azure api
